services:
  sftpgo:
    image: drakkan/sftpgo:latest-alpine
    container_name: sftpgo
    restart: unless-stopped
    ports:
      - "2022:2022" # SFTP
      - "2121:2121" # FTP
      - "8080:8080" # HTTP Admin Interface
      - "18080:18080" # WebDav
    volumes:
      - ./data:/home/user/.local/share/sftpgo # 數據持久化
    environment:
      - SFTPGODATA=/home/user/.local/share/sftpgo